name: makelint

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install eslint
      run: npm install --save-dev eslint
    
    - name: Run check
      run: make lint
