name: project-check

on:
  push:
    branches: [ main ]
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install project
      run: make install
    
    - name: run check
      run: make lint
